package entities;
// Generated Oct 27, 2017 9:43:57 PM by Hibernate Tools 4.3.1



/**
 * CongTy generated by hbm2java
 */
public class CongTy {


     private int msct;
     private String tenCongTy;
     private String diaChi;
     private String dienThoai;
     private String email;
     private String website;
     private String linhVucHoatDong;
     private String moTa;
     private String avatar;

    public CongTy() {
    }

	
    public CongTy(int msct) {
        this.msct = msct;
    }
    public CongTy(int msct, String tenCongTy, String diaChi, String dienThoai, String email, String website, String linhVucHoatDong) {
       this.msct = msct;
       this.tenCongTy = tenCongTy;
       this.diaChi = diaChi;
       this.dienThoai = dienThoai;
       this.email = email;
       this.website = website;
       this.linhVucHoatDong = linhVucHoatDong;
    }
   
    public int getMsct() {
        return this.msct;
    }
    
    public void setMsct(int msct) {
        this.msct = msct;
    }
    public String getTenCongTy() {
        return this.tenCongTy;
    }
    
    public void setTenCongTy(String tenCongTy) {
        this.tenCongTy = tenCongTy;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public String getLinhVucHoatDong() {
        return this.linhVucHoatDong;
    }
    
    public void setLinhVucHoatDong(String linhVucHoatDong) {
        this.linhVucHoatDong = linhVucHoatDong;
    }

    public String getMoTa() {
        return moTa;
    }

    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    
    



}


