package entities;
// Generated Oct 27, 2017 9:43:57 PM by Hibernate Tools 4.3.1



/**
 * DaiDienCongTy generated by hbm2java
 */
public class DaiDienCongTy  implements java.io.Serializable {


     private Integer id;
     private String hoTen;
     private String chucVu;
     private String diaChi;
     private String email;
     private String dienThoai;
     private int maCongTy;
     private String avatar;

    public DaiDienCongTy() {
    }

    public DaiDienCongTy(String hoTen, String chucVu, String diaChi, String email, String dienThoai) {
       this.hoTen = hoTen;
       this.chucVu = chucVu;
       this.diaChi = diaChi;
       this.email = email;
       this.dienThoai = dienThoai;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getChucVu() {
        return this.chucVu;
    }
    
    public void setChucVu(String chucVu) {
        this.chucVu = chucVu;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }

    public int getMaCongTy() {
        return maCongTy;
    }

    public void setMaCongTy(int maCongTy) {
        this.maCongTy = maCongTy;
    }

    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    



}


