package entities;
// Generated Oct 27, 2017 9:43:57 PM by Hibernate Tools 4.3.1



/**
 * DeTai generated by hbm2java
 */
public class DeTai  implements java.io.Serializable {


     private int id;
     private int maCongTy;
     private String tenDeTai;
     private String noiDung;
     private String yeuCau;
     private String nguoiDang;
     private Boolean trangThai;
     private int soLuong;
     private int gvhd;

    public DeTai() {
    }

    public DeTai(int maCongTy, String tenDeTai, String noiDung, String yeuCau, String nguoiDang, Boolean trangThai) {
       this.maCongTy = maCongTy;
       this.tenDeTai = tenDeTai;
       this.noiDung = noiDung;
       this.yeuCau = yeuCau;
       this.nguoiDang = nguoiDang;
       this.trangThai = trangThai;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getMaCongTy() {
        return this.maCongTy;
    }
    
    public void setMaCongTy(int maCongTy) {
        this.maCongTy = maCongTy;
    }
    public String getTenDeTai() {
        return this.tenDeTai;
    }
    
    public void setTenDeTai(String tenDeTai) {
        this.tenDeTai = tenDeTai;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }
    public String getYeuCau() {
        return this.yeuCau;
    }
    
    public void setYeuCau(String yeuCau) {
        this.yeuCau = yeuCau;
    }
    public String getNguoiDang() {
        return this.nguoiDang;
    }
    
    public void setNguoiDang(String nguoiDang) {
        this.nguoiDang = nguoiDang;
    }
    public Boolean getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(Boolean trangThai) {
        this.trangThai = trangThai;
    }

    public int getSoLuong() {
        return this.soLuong;
    }

    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }

    public int getGvhd() {
        return this.gvhd;
    }

    public void setGvhd(int gvhd) {
        this.gvhd = gvhd;
    }




}


