package entities;
// Generated Oct 27, 2017 9:43:57 PM by Hibernate Tools 4.3.1



/**
 * GiangVienChiTiet generated by hbm2java
 */
public class GiangVienChiTiet  implements java.io.Serializable {


     private int id;
     private String cacMonGiangDay;
     private String huongNghienCuu;
     private String cacCongTrinhNghienCuu;
     private String sachXuatBan;
     private String khac;

    public GiangVienChiTiet() {
    }

	
    public GiangVienChiTiet(int id) {
        this.id = id;
    }
    public GiangVienChiTiet(int id, String cacMonGiangDay, String huongNghienCuu, String cacCongTrinhNghienCuu, String sachXuatBan, String khac) {
       this.id = id;
       this.cacMonGiangDay = cacMonGiangDay;
       this.huongNghienCuu = huongNghienCuu;
       this.cacCongTrinhNghienCuu = cacCongTrinhNghienCuu;
       this.sachXuatBan = sachXuatBan;
       this.khac = khac;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCacMonGiangDay() {
        return this.cacMonGiangDay;
    }
    
    public void setCacMonGiangDay(String cacMonGiangDay) {
        this.cacMonGiangDay = cacMonGiangDay;
    }
    public String getHuongNghienCuu() {
        return this.huongNghienCuu;
    }
    
    public void setHuongNghienCuu(String huongNghienCuu) {
        this.huongNghienCuu = huongNghienCuu;
    }
    public String getCacCongTrinhNghienCuu() {
        return this.cacCongTrinhNghienCuu;
    }
    
    public void setCacCongTrinhNghienCuu(String cacCongTrinhNghienCuu) {
        this.cacCongTrinhNghienCuu = cacCongTrinhNghienCuu;
    }
    public String getSachXuatBan() {
        return this.sachXuatBan;
    }
    
    public void setSachXuatBan(String sachXuatBan) {
        this.sachXuatBan = sachXuatBan;
    }
    public String getKhac() {
        return this.khac;
    }
    
    public void setKhac(String khac) {
        this.khac = khac;
    }




}


