package entities;
// Generated Oct 27, 2017 9:43:57 PM by Hibernate Tools 4.3.1



/**
 * GiangVien generated by hbm2java
 */
public class GiangVien  implements java.io.Serializable {


     private Integer id;
     private String hoTen;
     private String diaChi;
     private String email;
     private String dienThoai;
     private String truong;
     private String khoaVien;
     private String avatar;

    public GiangVien() {
    }

    public GiangVien(String hoTen, String diaChi, String email, String dienThoai, String truong, String khoaVien, String avatar) {
       this.hoTen = hoTen;
       this.diaChi = diaChi;
       this.email = email;
       this.dienThoai = dienThoai;
       this.truong = truong;
       this.khoaVien = khoaVien;
       this.avatar = avatar;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }
    public String getTruong() {
        return this.truong;
    }
    
    public void setTruong(String truong) {
        this.truong = truong;
    }
    public String getKhoaVien() {
        return this.khoaVien;
    }
    
    public void setKhoaVien(String khoaVien) {
        this.khoaVien = khoaVien;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }




}


