package entities;
// Generated Oct 27, 2017 9:43:57 PM by Hibernate Tools 4.3.1



/**
 * GiangVienHuongDan generated by hbm2java
 */
public class GiangVienHuongDan  implements java.io.Serializable {


     private Integer id;
     private int msct;
     private String hoTen;
     private String chucVu;
     private String dienThoai;
     private String email;
     private String avatar;

    public GiangVienHuongDan() {
    }

    public GiangVienHuongDan(int msct, String hoTen, String chucVu, String dienThoai, String email, String avatar) {
       this.msct = msct;
       this.hoTen = hoTen;
       this.chucVu = chucVu;
       this.dienThoai = dienThoai;
       this.email = email;
       this.avatar = avatar;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getMsct() {
        return this.msct;
    }
    
    public void setMsct(int msct) {
        this.msct = msct;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getChucVu() {
        return this.chucVu;
    }
    
    public void setChucVu(String chucVu) {
        this.chucVu = chucVu;
    }
    public String getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }




}


