package entities;
// Generated Oct 27, 2017 9:43:57 PM by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private String email;
     private String password;
     private int rule;

    public Login() {
    }

    public Login(String email, String password, int rule) {
       this.email = email;
       this.password = password;
       this.rule = rule;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getRule() {
        return this.rule;
    }
    
    public void setRule(int rule) {
        this.rule = rule;
    }




}


