package entities;
// Generated Oct 27, 2017 9:43:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Logs generated by hbm2java
 */
public class Logs {


     private Integer id;
     private Date date;
     private String user;
     private String content;

    public Logs() {
    }

    public Logs(Date date, String user, String content) {
       this.date = date;
       this.user = user;
       this.content = content;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


