package entities;
// Generated Oct 27, 2017 9:43:57 PM by Hibernate Tools 4.3.1

/**
 * SinhVienDiem generated by hbm2java
 */
public class SinhVienDiem implements java.io.Serializable {

    private int mssv;
    private Double quaTrinh;
    private Double cuoiKy;
    private Double diemPhanHoi;
    private Double diemBaoCaoQuaTrinh;
    private Boolean trangThai;

    public SinhVienDiem() {
    }

    public SinhVienDiem(int mssv) {
        this.mssv = mssv;
    }

    public SinhVienDiem(int mssv, Double quaTrinh, Double cuoiKy, Boolean trangThai) {
        this.mssv = mssv;
        this.quaTrinh = quaTrinh;
        this.cuoiKy = cuoiKy;
        this.trangThai = trangThai;
    }

    public int getMssv() {
        return this.mssv;
    }

    public void setMssv(int mssv) {
        this.mssv = mssv;
    }

    public Double getQuaTrinh() {
        return this.quaTrinh;
    }

    public void setQuaTrinh(Double quaTrinh) {
        this.quaTrinh = quaTrinh;
    }

    public Double getCuoiKy() {
        return this.cuoiKy;
    }

    public void setCuoiKy(Double cuoiKy) {
        this.cuoiKy = cuoiKy;
    }

    public Boolean getTrangThai() {
        return this.trangThai;
    }

    public void setTrangThai(Boolean trangThai) {
        this.trangThai = trangThai;
    }

    public Double getDiemPhanHoi() {
        return diemPhanHoi;
    }

    public void setDiemPhanHoi(Double diemPhanHoi) {
        this.diemPhanHoi = diemPhanHoi;
    }

    public Double getDiemBaoCaoQuaTrinh() {
        return diemBaoCaoQuaTrinh;
    }

    public void setDiemBaoCaoQuaTrinh(Double diemBaoCaoQuaTrinh) {
        this.diemBaoCaoQuaTrinh = diemBaoCaoQuaTrinh;
    }

}
