package entities;
// Generated Oct 27, 2017 9:43:57 PM by Hibernate Tools 4.3.1



/**
 * SinhVienKnvaLt generated by hbm2java
 */
public class SinhVienKnvaLt  implements java.io.Serializable {


     private int mssv;
     private String kyNang;
     private String lapTrinh;

    public SinhVienKnvaLt() {
    }

    public SinhVienKnvaLt(String kyNang, String lapTrinh) {
       this.kyNang = kyNang;
       this.lapTrinh = lapTrinh;
    }
   
    public int getMssv() {
        return this.mssv;
    }
    
    public void setMssv(int mssv) {
        this.mssv = mssv;
    }
    public String getKyNang() {
        return this.kyNang;
    }
    
    public void setKyNang(String kyNang) {
        this.kyNang = kyNang;
    }
    public String getLapTrinh() {
        return this.lapTrinh;
    }
    
    public void setLapTrinh(String lapTrinh) {
        this.lapTrinh = lapTrinh;
    }




}


