package entities;
// Generated Oct 27, 2017 9:43:57 PM by Hibernate Tools 4.3.1



/**
 * SinhVienThucTap generated by hbm2java
 */
public class SinhVienThucTap  implements java.io.Serializable {


    private int id;
     private int mssv;
     private String thoiGianBatDau;
     private String thoiGianKetThuc;
     private int maCongTy;
     private int nguoiHuongDan;
     private int maDeTai;
     private boolean trangThai;
     private double soKhop;

    public SinhVienThucTap() {
    }

	
    public SinhVienThucTap(int mssv) {
        this.mssv = mssv;
    }
    public SinhVienThucTap(int mssv, String thoiGianBatDau, String thoiGianKetThuc, int maCongTy, int nguoiHuongDan, int maDeTai) {
       this.mssv = mssv;
       this.thoiGianBatDau = thoiGianBatDau;
       this.thoiGianKetThuc = thoiGianKetThuc;
       this.maCongTy = maCongTy;
       this.nguoiHuongDan = nguoiHuongDan;
       this.maDeTai = maDeTai;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
   
    public int getMssv() {
        return this.mssv;
    }
    
    public void setMssv(int mssv) {
        this.mssv = mssv;
    }
    public String getThoiGianBatDau() {
        return this.thoiGianBatDau;
    }
    
    public void setThoiGianBatDau(String thoiGianBatDau) {
        this.thoiGianBatDau = thoiGianBatDau;
    }
    public String getThoiGianKetThuc() {
        return this.thoiGianKetThuc;
    }
    
    public void setThoiGianKetThuc(String thoiGianKetThuc) {
        this.thoiGianKetThuc = thoiGianKetThuc;
    }
    public int getMaCongTy() {
        return this.maCongTy;
    }
    
    public void setMaCongTy(int maCongTy) {
        this.maCongTy = maCongTy;
    }
    public int getNguoiHuongDan() {
        return this.nguoiHuongDan;
    }
    
    public void setNguoiHuongDan(int nguoiHuongDan) {
        this.nguoiHuongDan = nguoiHuongDan;
    }
    public int getMaDeTai() {
        return this.maDeTai;
    }
    
    public void setMaDeTai(int maDeTai) {
        this.maDeTai = maDeTai;
    }

    public boolean isTrangThai() {
        return trangThai;
    }

    public void setTrangThai(boolean trangThai) {
        this.trangThai = trangThai;
    }

    public double getSoKhop() {
        return soKhop;
    }

    public void setSoKhop(double soKhop) {
        this.soKhop = soKhop;
    }




}


