package entities;
// Generated Oct 27, 2017 9:43:57 PM by Hibernate Tools 4.3.1

import java.util.Date;




/**
 * SinhVienFile generated by hbm2java
 */
public class SinhVienFile  implements java.io.Serializable {


     private int id;
     private int mssv;
     private String tenFile;
     private String link;
     private int loaiFile;
     private Date ngayThang;

    public SinhVienFile() {
    }

	
    public SinhVienFile(int id) {
        this.id = id;
    }

    public SinhVienFile(int id, int mssv, String tenFile, String link, int loaiFile) {
        this.id = id;
        this.mssv = mssv;
        this.tenFile = tenFile;
        this.link = link;
        this.loaiFile = loaiFile;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getMssv() {
        return this.mssv;
    }

    public void setMssv(int mssv) {
        this.mssv = mssv;
    }

    public String getTenFile() {
        return this.tenFile;
    }

    public void setTenFile(String tenFile) {
        this.tenFile = tenFile;
    }

    public String getLink() {
        return this.link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public int getLoaiFile() {
        return this.loaiFile;
    }

    public void setLoaiFile(int loaiFile) {
        this.loaiFile = loaiFile;
    }

    public Date getNgayThang() {
        return this.ngayThang;
    }

    public void setNgayThang(Date ngayThang) {
        this.ngayThang = ngayThang;
    }
    
    




}


