package entities;
// Generated Oct 27, 2017 9:43:57 PM by Hibernate Tools 4.3.1



/**
 * SinhVienMucTieu generated by hbm2java
 */
public class SinhVienMucTieu  implements java.io.Serializable {


     private int mssv;
     private String viTriMongMuon;
     private String loaiCongViec;
     private String nganhNgheMongMuon;
     private String noiLamViecYeuThich;
     private String khac;

    public SinhVienMucTieu() {
    }

	
    public SinhVienMucTieu(int mssv) {
        this.mssv = mssv;
    }
    public SinhVienMucTieu(int mssv, String viTriMongMuon, String loaiCongViec, String nganhNgheMongMuon, String noiLamViecYeuThich, String khac) {
       this.mssv = mssv;
       this.viTriMongMuon = viTriMongMuon;
       this.loaiCongViec = loaiCongViec;
       this.nganhNgheMongMuon = nganhNgheMongMuon;
       this.noiLamViecYeuThich = noiLamViecYeuThich;
       this.khac = khac;
    }
   
    public int getMssv() {
        return this.mssv;
    }
    
    public void setMssv(int mssv) {
        this.mssv = mssv;
    }
    public String getViTriMongMuon() {
        return this.viTriMongMuon;
    }
    
    public void setViTriMongMuon(String viTriMongMuon) {
        this.viTriMongMuon = viTriMongMuon;
    }
    public String getLoaiCongViec() {
        return this.loaiCongViec;
    }
    
    public void setLoaiCongViec(String loaiCongViec) {
        this.loaiCongViec = loaiCongViec;
    }
    public String getNganhNgheMongMuon() {
        return this.nganhNgheMongMuon;
    }
    
    public void setNganhNgheMongMuon(String nganhNgheMongMuon) {
        this.nganhNgheMongMuon = nganhNgheMongMuon;
    }
    public String getNoiLamViecYeuThich() {
        return this.noiLamViecYeuThich;
    }
    
    public void setNoiLamViecYeuThich(String noiLamViecYeuThich) {
        this.noiLamViecYeuThich = noiLamViecYeuThich;
    }
    public String getKhac() {
        return this.khac;
    }
    
    public void setKhac(String khac) {
        this.khac = khac;
    }




}


