package entities;
// Generated Oct 27, 2017 9:43:57 PM by Hibernate Tools 4.3.1

import java.util.Date;




/**
 * SinhVienThucTap generated by hbm2java
 */
public class SinhVienThucTap  implements java.io.Serializable {


    private int id;
     private int mssv;
     private Date thoiGianBatDau;
     private Date thoiGianKetThuc;
     private int maCongTy;
     private int nguoiHuongDan;
     private int maDeTai;
     private int trangThai;
     private double soKhop;
     private boolean soLanThucTap;
     private boolean hoatDong;

    public SinhVienThucTap() {
    }

	
    public SinhVienThucTap(int mssv) {
        this.mssv = mssv;
    }
    public SinhVienThucTap(int mssv, Date thoiGianBatDau, Date thoiGianKetThuc, int maCongTy, int nguoiHuongDan, int maDeTai) {
       this.mssv = mssv;
       this.thoiGianBatDau = thoiGianBatDau;
       this.thoiGianKetThuc = thoiGianKetThuc;
       this.maCongTy = maCongTy;
       this.nguoiHuongDan = nguoiHuongDan;
       this.maDeTai = maDeTai;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
   
    public int getMssv() {
        return this.mssv;
    }
    
    public void setMssv(int mssv) {
        this.mssv = mssv;
    }
    public Date getThoiGianBatDau() {
        return this.thoiGianBatDau;
    }
    
    public void setThoiGianBatDau(Date thoiGianBatDau) {
        this.thoiGianBatDau = thoiGianBatDau;
    }
    public Date getThoiGianKetThuc() {
        return this.thoiGianKetThuc;
    }
    
    public void setThoiGianKetThuc(Date thoiGianKetThuc) {
        this.thoiGianKetThuc = thoiGianKetThuc;
    }
    public int getMaCongTy() {
        return this.maCongTy;
    }
    
    public void setMaCongTy(int maCongTy) {
        this.maCongTy = maCongTy;
    }
    public int getNguoiHuongDan() {
        return this.nguoiHuongDan;
    }
    
    public void setNguoiHuongDan(int nguoiHuongDan) {
        this.nguoiHuongDan = nguoiHuongDan;
    }
    public int getMaDeTai() {
        return this.maDeTai;
    }
    
    public void setMaDeTai(int maDeTai) {
        this.maDeTai = maDeTai;
    }

    public int getTrangThai() {
        return trangThai;
    }

    public void setTrangThai(int trangThai) {
        this.trangThai = trangThai;
    }

    public double getSoKhop() {
        return soKhop;
    }

    public void setSoKhop(double soKhop) {
        this.soKhop = soKhop;
    }

    public boolean getSoLanThucTap() {
        return soLanThucTap;
    }

    public void setSoLanThucTap(boolean soLanThucTap) {
        this.soLanThucTap = soLanThucTap;
    }

    public boolean getHoatDong() {
        return hoatDong;
    }

    public void setHoatDong(boolean hoatDong) {
        this.hoatDong = hoatDong;
    }

    


}


