package entities;
// Generated Oct 27, 2017 9:43:57 PM by Hibernate Tools 4.3.1

import java.util.Date;




/**
 * ThongBao generated by hbm2java
 */
public class ThongBao  implements java.io.Serializable {


     private int id;
     private String tieuDe;
     private Date thoiGian;
     private String noiDung;
     private String nguoiDang;

    public ThongBao() {
    }

	
    public ThongBao(int id) {
        this.id = id;
    }
    public ThongBao(int id, String tieuDe, Date thoiGian, String noiDung, String nguoiDang) {
       this.id = id;
       this.tieuDe = tieuDe;
       this.thoiGian = thoiGian;
       this.noiDung = noiDung;
       this.nguoiDang = nguoiDang;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(String tieuDe) {
        this.tieuDe = tieuDe;
    }
    public Date getThoiGian() {
        return this.thoiGian;
    }
    
    public void setThoiGian(Date thoiGian) {
        this.thoiGian = thoiGian;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }
    public String getNguoiDang() {
        return this.nguoiDang;
    }
    
    public void setNguoiDang(String nguoiDang) {
        this.nguoiDang = nguoiDang;
    }

}


